[package]
name = "coordinate-transformer"
version = "1.0.0"
authors = ["azishio"]
edition = "2021"
description = "A library for transforming coordinates between longitude_latitude, JPR, and pixel."

documentation = "https://docs.rs/coordinate-transformer"
homepage = "https://crates.io/crates/coordinate-transformer"
repository = "https://github.com/azishio/coordinate-transformer-rs"

readme = "README.md"

keywords = ["longitude", "latitude", "jpr", "pixel"]
categories = ["mathematics", "science::geo"]
license = "MIT"
